config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cards
  resources :scores

  namespace :admin do
    resources :cards do
      resource :effect, only: :show
    end
  end

  root "scores#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :card_types
  has_many :types, through: :card_types

  scope :colour_search, ->(value) { value.present? ? where(colour: value) : self }
  scope :collection_search, ->(value) { value.present? ? where(collection: value) : self }
  scope :state_search, ->(value) do
    case value.to_sym
    when :processed
      where(effect: [nil, '']).or(where.not("effects::text in ('{}', '[]')"))
    when :unprocessed
      where.not(effect: [nil, '']).where("effects::text in ('{}', '[]')")
    else
      self
    end
  end
  scope :name_search, ->(value) { value.present? ? where("name ILIKE ?", "%#{value}%") : self }
end

app/models/card_type.rb
class CardType < ApplicationRecord
  belongs_to :card
  belongs_to :type
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :previous_game, class_name: "Game", required: false

  has_many :players
  has_many :users, through: :players

  def update_card!(card:, user:, event_type: )
    self.cards ||= {}
    user_cards = cards[user.id] ||= {}
    card_data = user_cards[card.id] ||= {
      "card_id" => card.id,
      "owner" => user.id,
      "actions" => "???",
      "count" => 0
    }
    modifier = case event_type
      when "add_card" then 1
      when "remove_card" then -1
      when "remove_all" then -card_data["count"]
      end

    card_data["count"] += modifier
    cards[user.id].delete(card.id) if card_data["count"] < 1
    save!
  end

  def users_and_data(user_ids=nil)
    self.cards ||= {}

    card_ids = cards.values.flat_map(&:keys)
    card_records = Card.where(id: card_ids).index_by(&:id)

    filtered_users = users
    filtered_users = filtered_users.where(id: user_ids) if user_ids

    filtered_users.map do |user|
      [
        user,
        score(card_records, user),
        (cards[user.id] || {}).
          map { |card_id, card_data| [card_records[card_id], card_data] }.
          sort_by { |card, _| card.name },
      ]
    end
  end

  def score(cards_records, user)
    card_value = cards.fetch(user.id, []).
      sum { |card_id, _card_data| cards_records[card_id]&.points || 0 }

    # actually calculate this based on card types
    bonus_points = 0

    card_value + bonus_points
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :card_types
  has_many :cards, through: :card_types
end

app/models/user.rb
class User < ApplicationRecord
  class << self
    def generate_name
      [colour, animal, rand(100_000)].join("-")
    end

    def animal
      %i[
        Dog Cow Cat Horse Donkey Tiger Lion Panther Leopard Cheetah Bear Elephant
        Polar-bear Turtle Tortoise Crocodile Rabbit Porcupine Hare Hen Otter
        Pigeon Albatross Crow Fish Dolphin Frog Whale Alligator Jellyfish Mammoth
        Eagle squirrel Ostrich Fox Goat Jackal Emu Armadillo Hippopotamus
        Eel Goose Arctic-fox Wolf Beagle Chimpanzee Monkey Beaver Orangutan Antelope Bat
        Badger Giraffe Crab Panda Hamster Cobra Shark Camel Hawk Deer Chameleon
        Jaguar Chihuahua Ibex Lizard Koala Kangaroo Iguana Llama Chinchillas Dodo
        Rhinoceros Hedgehog Zebra Possum Wombat Bison Bull Buffalo Sheep Meerkat Mouse
        Sloth Owl Vulture Flamingo Racoon Mole Duck Swan Lynx Elk Boar Lemur Mule Baboon
        Blue-whale Rat Snake Peacock
      ].sample
    end

    def colour
      %i[
        White Yellow Blue Red Green Black Brown Azure Ivory Teal Silver Purple Gray
        Orange Maroon Charcoal Aquamarine Coral Fuchsia Wheat Lime Crimson Khaki
        Pink Magenta Olden Plum Olive Cyan
      ].sample
    end
  end
end

app/controllers/admin/cards_controller.rb
module Admin
  class CardsController < ApplicationController
    layout "admin"
    def index
      search = CardSearch.new(search_params)

      pagy, cards = pagy(search.apply(Card.includes(:types).order(:name)))
      render :index, locals: { pagy: pagy, cards: cards, search: search }
    end

    def show
      card =
        case params[:select]
        when "previous"
          prev = Card.find(params[:id])
          Card.order(name: :desc).where("name < ?", prev.name).first
        when "next"
          prev = Card.find(params[:id])
          Card.order(name: :asc).where("name > ?", prev.name).first
        else
          Card.find(params[:id])
        end

      render :show, locals: { card: card }
    end

    def update
      card = Card.find(params[:id])
      card.update(update_params)

      redirect_to admin_card_path(card)
    end

    private

    def search_params
      params.fetch(:card_search, {}).permit(:colour, :collection, :state, :name)
    end

    def update_params
      params.require(:card).permit(
        effects: [
          :has_effect, # attributes
          :type,
          :effect_count, # effect_count
          :trait_colour, :trait_count, #trait_count
        ]
      )
    end
  end
end

app/controllers/admin/effects_controller.rb
module Admin
  class EffectsController < ApplicationController
    layout false

    def show
      card = Card.find(params[:card_id])
      effect = params[:effect] || card.effects["type"] || "none"
      card.effects[:type] = effect
      render effect, locals: { card: card }
    end

    private

    def search_params
      params.fetch(:card_search, {}).permit(:colour, :collection, :state, :name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user

  def current_user
    if cookies[:user]
      user = User.find_by(id: cookies[:user])
      return user if user
    end

    user = User.create(name: User.generate_name)
    cookies[:user] = user.id
    user
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show

  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index

  end

  def new
    puts params
    game_name = params.fetch(:game_name, User.generate_name)
    game = Game.find_or_create_by(name: game_name, decks: ["Classic"])
    game.users << current_user

    redirect_to score_path(game.name)
  end

  def show
    game = Game.find_by!(name: params[:id])
    game.users |= [current_user]
    cards = Card.where(collection: game.decks).order(:colour, :name)

    render :show, locals: { game: game, cards: cards }
  end

  def update
    game = Game.find_by!(name: params[:id])
    card = Card.find(params[:card])
    user = User.find(params[:user_id])

    game.update_card!(card: card, user: user, event_type: params[:event_type])

    render :update, locals: { game: game, user: user }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/admin/cards/index.html.erb
<%= form_with model: search, url: admin_cards_path, local: true, method: :get do |f| %>
  <div class="flex">
    <div>
      <%= f.label :colour %>
      <%= f.select :colour, search.colours, { include_blank: true } %>
    </div>
    <div>
      <%= f.label :collection %>
      <%= f.select :collection, search.collections, { include_blank: true } %>
    </div>
    <div>
      <%= f.label :state %>
      <%= f.select :state, search.states %>
    </div>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.submit :search %>
    </div>
  </div>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Points</th>
    <th>Colour</th>
    <th>Type(s)</th>
    <th>Collection</th>
    <th>Configured</th>
    <th>Effects</th>
  </tr>
  <% cards.each do |card| %>
    <tr>
      <td><%= link_to card.name, admin_card_path(card) %></td>
      <td><%= card.points %></td>
      <td><%= card.colour %></td>
      <td><%= card.types.map(&:name).join(", ") %></td>
      <td><%= card.collection %></td>
      <td><%= card.effect.blank? || card.effects.present? %></td>
      <td>
        <% card.effect.split("\n") do |effect| %>
          <%= effect %>
          <br>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%== pagy_nav(pagy) %>

app/views/admin/cards/show.html.erb
<%= form_with model: card, url: admin_card_path(card), local: true do |f| %>
  <div class="grid grid-cols-5">
    <div class="m-4 p-2 bg-gray-100 row-span-3 rounded-xl flex justify-center">
      <%= image_tag("cards/#{card.name}", class: "h-64 m-auto") %>
    </div>

    <div class="m-4 p-2 bg-gray-100 col-span-2 rounded-xl">
      <%= f.label :name, class: "text-gray-400" %><br>
      <%= card.name %>
    </div>
    <div class="m-4 p-2 bg-gray-100 col-span-2 rounded-xl">
      <%= f.label :favour, class: "text-gray-400" %><br>
      <%= card.favour %>
    </div>
    <div class="m-4 p-2 bg-gray-100 col-span-2 rounded-xl">
      <%= f.label :effect, class: "text-gray-400" %><br>
      <% card.effect.split("\n").each do |effect| %>
        <%= effect %><br>
      <% end %>
    </div>
    <div class="m-4 p-2 bg-gray-100 col-span-2 rounded-xl">
      <%= f.label :points, class: "text-gray-400" %><br>
      <%= card.points || "N/A" %>
    </div>
    <div class="m-4 p-2 bg-gray-100 col-span-2 rounded-xl">
      <%= f.label :colour, class: "text-gray-400" %><br>
      <%= card.colour %>
    </div>
    <div class="m-4 p-2 bg-gray-100 col-span-2 rounded-xl">
      <%= f.label :collection, class: "text-gray-400" %><br>
      <%= card.collection %>
    </div>

    <%= turbo_frame_tag "card_effects", src: admin_card_effect_path(card), class: "col-span-5 m-4 rounded-xl overflow-hidden border border-gray-700" %>

    <div class="m-4 mb-0 col-span-5 flex bg-green-200 border border-gray-700 rounded-t-xl overflow-hidden">
      <div class="font-bolder py-2 px-5 bg-green-500">
        Attributes:
      </div>
    </div>
    <div class="m-4 mt-0 col-span-5 grid grid-cols-2 bg-gray-300 border border-t-0 border-gray-700 rounded-b-xl">
      <%= f.fields :effects, model: OpenStruct.new(f.object.effects) do |e| %>
        <div class="font-bolder py-2 px-5 border-0 border-gray-700">
          <%= e.label :has_effect, class: "pr-5" %>
          <%= e.check_box :has_effect %>
        </div>
      <% end %>
    </div>

    <div class="m-4 bg-gray-200 hover:bg-gray-500 hover:text-white col-span-1 flex justify-center rounded-full border border-gray-700">
      <%= f.submit :update, class: "m-2 w-full text-center block uppercase" %>
    </div>
    <div class="m-4 bg-gray-200 hover:bg-gray-500 hover:text-white col-span-1 flex justify-center rounded-full border border-gray-700">
      <%= link_to :previous, admin_card_path(card, select: "previous"), class: "m-2 w-full text-center block uppercase" %>
    </div>
    <div class="m-4 bg-gray-200 hover:bg-gray-500 hover:text-white col-span-1 flex justify-center rounded-full border border-gray-700">
      <%= link_to :next, admin_card_path(card, select: "next"), class: "m-2 w-full text-center block uppercase" %>
    </div>
  </div>
<% end %>

app/views/admin/effects/_effects.html.erb
<%= e.hidden_field :type %>

<div class="flex bg-green-200 border-b border-gray-700">
  <div class="font-bolder py-2 px-5 bg-green-500">
    EFFECTS:
  </div>
  <div class="py-2 px-5 <%= "bg-red-200 font-red-900" if effect == "none" %>">
    <%= link_to "None", admin_card_effect_url(card, effect: "none") %>
  </div>
  <div class="py-2 px-5 <%= "bg-red-200 font-red-900" if effect == "effect_count" %>">
    <%= link_to "Effect Count", admin_card_effect_url(card, effect: "effect_count") %>
  </div>
  <div class="py-2 px-5 <%= "bg-red-200 font-red-900" if effect == "trait_count" %>">
    <%= link_to "Trait Count", admin_card_effect_url(card, effect: "trait_count") %>
  </div>
</div>

app/views/admin/effects/effect_count.html.erb
<%= form_with model: card, url: admin_card_path(card), local: true do |f| %>
  <%= f.fields :effects, model: OpenStruct.new(f.object.effects) do |e| %>
    <%= turbo_frame_tag "card_effects" do %>
      <%= render partial: "admin/effects/effects", locals: { card: card, effect: "effect_count", e: e } %>

      <div class="bg-gray-300 p-2 border-b border-gray-700">
        Points based on the number of cards with effects in your hand
      </div>
      <div class="bg-gray-300 p-2 ">
        <%= e.label :effect_count, "Enter effect count as json hash, for all values great used {value}+" %><br>

        <%= e.text_area :effect_count, class: "w-full h-52" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/admin/effects/none.html.erb
<%= form_with model: card, url: admin_card_path(card), local: true do |f| %>
  <%= f.fields :effects, model: OpenStruct.new(f.object.effects) do |e| %>
    <%= turbo_frame_tag "card_effects" do %>
      <%= render partial: "admin/effects/effects", locals: { card: card, effect: "none", e: e } %>

      <div class="bg-gray-300 p-2">
        This Card has no effect on the final score outside of it points
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/admin/effects/trait_count.html.erb
<%= form_with model: card, url: admin_card_path(card), local: true do |f| %>
  <%= f.fields :effects, model: OpenStruct.new(f.object.effects) do |e| %>
    <%= turbo_frame_tag "card_effects" do %>
      <%= render partial: "admin/effects/effects", locals: { card: card, effect: "trait_count", e: e } %>

      <div class="bg-gray-300 p-2 border-b border-gray-700">
        Points based on the number of cards with effects in your hand
      </div>
      <div class="bg-gray-300 p-2 ">
        <%= e.label :trait_colour, "Trait Colour" %><br>

        <%= e.select :trait_colour, ["Any"] + Card.distinct.pluck(:colour).sort, { include_blank: true } %>
      </div>
      <div class="bg-gray-300 p-2 ">
        <%= e.label :trait_count, "Enter trait count as json hash, for all values great used {value}+" %><br>

        <%= e.text_area :trait_count, class: "w-full h-52" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoomingsScore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <main class="container mx-auto px-5 bg-white">
      <div class="text-3xl bg-blue-300 border-b-4 border-blue-600 p-5 mb-5 -mx-5">Admin</div>
      <%= yield %>

    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoomingsScore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto bg-gradient-to-r from-green-400 to-blue-500 h-full min-h-screen">
      <div class="flex bg-gray-700 p-2">
        <div class="align-right text-white">
          <%= current_user.name %>
        </div>
      </div>
      <div class="px-2 pt-5">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/scores/_user.html.erb
<div id="User-<%= user.id %>" do %>
  <div class="bg-gray-300">
    <div class="<%= "selected-user bg-red-700 text-white" if visible %> px-2 py-1" data-tabs-target="tab"
         data-action="click->tabs#change" data-user-id="<%= user.id %>" data-test-id="user-<%= user.id %>">
      <div class="text-base font-bold"><%= user.name %></div>
      Score: <%= score %> Cards: <%= cards.sum { |_, card| card["count"] } %>
    </div>
  </div>
  <div class="<%= "hidden" unless visible %> cards min-h-0 overflow-y-scroll" data-tabs-target="panel">
    <% cards.each do |card, card_data| %>
      <div class="border-b px-2 py-1 flex flex-row" data-controller="card-selector">
        <div class="bg-<%= card.colour == "Colorless" ? "gray" : card.colour.downcase %>-400 border border-white rounded-full w-4 h-4 mr-1 flex justify-center">
          &nbsp;
        </div>
        <div class="flex-grow overflow-hidden overflow-ellipsis min-w-0">
          <%= card.name %> (<%= card_data["count"] %>)
        </div>
        <div class="place-self-end bg-white rounded-full w-4 flex justify-center">
          <%= link_to "X", score_path(game.name, card: card.id), method: :delete, class: "text-red-600",
            "data-test-id": "remove-all-#{user.id}-#{card.name}",
            "data-card-selector-target": "submit", "data-action": "card-selector#delete"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/scores/index.html.erb
<div class="text-3xl lg:text-6xl text-bolder text-blue-700 p-4 pb-2">
  Doomlings Score Calculator
</div>
<div class="text-lg lg:text-2xl text-bolder text-purple-600 p-4 pt-0">
  Because why do it yourself
</div>
<div class="space-y-px h-full items-center">
  <div class="text-center text-2xl lg:text-4xl my-8 lg:my-0 lg:h-1/4 flex items-center justify-center">
    <%= link_to "Score a new Game", new_score_path, class: "text-gray-700 hover:text-blue-600 no-underline" %>
  </div>

  <div class="text-center text-2xl lg:text-4xl my-8 lg:my-0 lg:h-1/4 flex items-center justify-center">
    <div class="inline-block">
    <%= form_tag new_score_path, method: :get do %>
      <%= submit_tag "Add your score to a game", class: "text-gray-700 hover:text-blue-600 no-underline" %><br>
      <%= text_field_tag :game_name, nil, class: "rounded-xl mt-5", placeholder: "Game Name"  %>
    <% end %>
      </div>
  </div>
</div>

app/views/scores/show.html.erb
<div class="px-2 py-1 text-base font-bold" data-tabs-target="tab" data-action="click->tabs#change">
  Game: <%= game.name %>
</div>

<div class="grid grid-cols-2 text-xs">
  <div class="border flex flex-col max-h-80vh" data-controller="tabs" data-tabs-active-tab="selected-colour bg-red-700 text-white">
    <% cards.group_by(&:colour).each do |colour, cards_for_colour| %>
      <div class="bg-gray-300">
        <div class="px-2 py-1 text-base font-bold" data-tabs-target="tab" data-action="click->tabs#change">
          <%= colour %>
        </div>
      </div>
      <div class="hidden cards min-h-0 overflow-y-scroll" data-tabs-target="panel">
        <% cards_for_colour.each do |card| %>
          <div class="border-b flex py-1 px-2" data-controller="card-selector">
            <div class="flex-grow">
              <%= card.name %>
            </div>
            <div class="justify-self-end flex justify-center">
              <%= link_to score_path(game.name, card: card.id), method: :patch,
                "data-card-selector-target": "submit", "data-action": "card-selector#add",
                "data-test-id": "add-card-#{card.name}",
                class: "px-2  border border-green-800 bg-green-400 text-white -bold text-xl mr-2 leading-5" do %>
                +
              <% end %>
              <%= link_to score_path(game.name, card: card.id), method: :patch,
                "data-card-selector-target": "submit", "data-action": "card-selector#remove",
                "data-test-id": "remove-card-#{card.name}",
                class: "px-2 border border-red-800 bg-red-400 text-white font-bold text-xl leading-5" do %>
                -
              <% end %>

            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="border flex flex-col max-h-60vh" data-controller="tabs" data-tabs-active-tab="selected-user bg-red-700 text-white" data-test-id="players">
    <% game.users_and_data.each do |user, score, cards| %>
      <%= render "user", game: game, user: user, score: score, cards: cards, visible: false %>
    <% end %>
  </div>
</div>

app/views/scores/update.html.erb
<turbo-stream action="replace" target="User-<%= user.id %>">
  <template>
    <% game.users_and_data(user.id).each do |user, score, cards| %>
      <%= render "user", game: game, user: user, score: score, cards: cards, visible: true %>
    <% end %>
  </template>
</turbo-stream>